import { Catch, ExceptionFilter, ArgumentsHost, HttpStatus } from '@nestjs/common';
import { HttpException } from '@nestjs/common/exceptions/http.exception';
import { Logger } from '@nestjs/common';

@Catch()
export class AllExceptionsFilter implements ExceptionFilter {
  private readonly logger = new Logger(AllExceptionsFilter.name);

  catch(exception: any, host: ArgumentsHost) {
    const ctx = host.switchToHttp();
    const response = ctx.getResponse();
    const request = ctx.getRequest();

    if (exception instanceof HttpException) {
      const status = exception.getStatus();
      const message = exception.message;
      const responses: any = exception.getResponse();

      if (status === HttpStatus.BAD_REQUEST) {
        response.status(status).json({
          statusCode: status,
          message: typeof responses === 'object' ? responses.message : message,
          error: exception.name,
        });
      }

      if (status === HttpStatus.NOT_FOUND || status === HttpStatus.BAD_REQUEST) {
        response.status(status).json({
          statusCode: status,
          message,
          error: exception.name,
        });
      } else {
        response.status(status).json({
          statusCode: status,
          timestamp: new Date().toISOString(),
          path: request.url,
          message,
        });
      }
    } else {
      this.logger.error(exception);
      response.status(HttpStatus.INTERNAL_SERVER_ERROR).json({
        message: 'Ocurri√≥ un error:  inesperado',
      });
    }
  }
}
